//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Types.Game.Context.Roleplay
{
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class HumanOptionAlliance : HumanOption
    {
        
        public new const short ProtocolId = 425;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private AllianceInformations m_allianceInformations;
        
        public virtual AllianceInformations AllianceInformations
        {
            get
            {
                return m_allianceInformations;
            }
            set
            {
                m_allianceInformations = value;
            }
        }
        
        private byte m_aggressable;
        
        public virtual byte Aggressable
        {
            get
            {
                return m_aggressable;
            }
            set
            {
                m_aggressable = value;
            }
        }
        
        public HumanOptionAlliance(AllianceInformations allianceInformations, byte aggressable)
        {
            m_allianceInformations = allianceInformations;
            m_aggressable = aggressable;
        }
        
        public HumanOptionAlliance()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
            m_allianceInformations.Serialize(writer);
            writer.WriteByte(m_aggressable);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
            m_allianceInformations = new AllianceInformations();
            m_allianceInformations.Deserialize(reader);
            m_aggressable = reader.ReadByte();
        }
    }
}
