//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Actions.Sequence
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.IO;
    
    
    public class SequenceStartMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 955;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_sequenceType;
        
        public virtual byte SequenceType
        {
            get
            {
                return m_sequenceType;
            }
            set
            {
                m_sequenceType = value;
            }
        }
        
        private double m_authorId;
        
        public virtual double AuthorId
        {
            get
            {
                return m_authorId;
            }
            set
            {
                m_authorId = value;
            }
        }
        
        public SequenceStartMessage(byte sequenceType, double authorId)
        {
            m_sequenceType = sequenceType;
            m_authorId = authorId;
        }
        
        public SequenceStartMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteByte(m_sequenceType);
            writer.WriteDouble(m_authorId);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_sequenceType = reader.ReadByte();
            m_authorId = reader.ReadDouble();
        }
    }
}
