//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Types.Game.Context
{
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class MapCoordinates : NetworkType
    {
        
        public const short ProtocolId = 174;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private short m_worldX;
        
        public virtual short WorldX
        {
            get
            {
                return m_worldX;
            }
            set
            {
                m_worldX = value;
            }
        }
        
        private short m_worldY;
        
        public virtual short WorldY
        {
            get
            {
                return m_worldY;
            }
            set
            {
                m_worldY = value;
            }
        }
        
        public MapCoordinates(short worldX, short worldY)
        {
            m_worldX = worldX;
            m_worldY = worldY;
        }
        
        public MapCoordinates()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteShort(m_worldX);
            writer.WriteShort(m_worldY);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_worldX = reader.ReadShort();
            m_worldY = reader.ReadShort();
        }
    }
}
