//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Fight.Character
{
    using Cookie.API.Protocol.Network.Types.Game.Context.Fight;
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.IO;
    
    
    public class GameFightShowFighterRandomStaticPoseMessage : GameFightShowFighterMessage
    {
        
        public new const uint ProtocolId = 6218;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        public GameFightShowFighterRandomStaticPoseMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
        }
    }
}
