//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Roleplay.Havenbag
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.IO;
    
    
    public class RoomAvailableUpdateMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6630;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private sbyte m_nbRoom;
        
        public virtual sbyte NbRoom
        {
            get
            {
                return m_nbRoom;
            }
            set
            {
                m_nbRoom = value;
            }
        }
        
        public RoomAvailableUpdateMessage(sbyte nbRoom)
        {
            m_nbRoom = nbRoom;
        }
        
        public RoomAvailableUpdateMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteSByte(m_nbRoom);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_nbRoom = reader.ReadSByte();
        }
    }
}
