//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Approach
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class AccountLoggingKickedMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6029;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_days;
        
        public virtual ushort Days
        {
            get
            {
                return m_days;
            }
            set
            {
                m_days = value;
            }
        }
        
        private byte m_hours;
        
        public virtual byte Hours
        {
            get
            {
                return m_hours;
            }
            set
            {
                m_hours = value;
            }
        }
        
        private byte m_minutes;
        
        public virtual byte Minutes
        {
            get
            {
                return m_minutes;
            }
            set
            {
                m_minutes = value;
            }
        }
        
        public AccountLoggingKickedMessage(ushort days, byte hours, byte minutes)
        {
            m_days = days;
            m_hours = hours;
            m_minutes = minutes;
        }
        
        public AccountLoggingKickedMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhShort(m_days);
            writer.WriteByte(m_hours);
            writer.WriteByte(m_minutes);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_days = reader.ReadVarUhShort();
            m_hours = reader.ReadByte();
            m_minutes = reader.ReadByte();
        }
    }
}
