//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Inventory.Items
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class MimicryObjectErrorMessage : SymbioticObjectErrorMessage
    {
        
        public new const uint ProtocolId = 6461;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private bool m_preview;
        
        public virtual bool Preview
        {
            get
            {
                return m_preview;
            }
            set
            {
                m_preview = value;
            }
        }
        
        public MimicryObjectErrorMessage(bool preview)
        {
            m_preview = preview;
        }
        
        public MimicryObjectErrorMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
            writer.WriteBoolean(m_preview);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
            m_preview = reader.ReadBoolean();
        }
    }
}
