//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Types.Game.Character.Status
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class PlayerStatus : NetworkType
    {
        
        public const short ProtocolId = 415;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_statusId;
        
        public virtual byte StatusId
        {
            get
            {
                return m_statusId;
            }
            set
            {
                m_statusId = value;
            }
        }
        
        public PlayerStatus(byte statusId)
        {
            m_statusId = statusId;
        }
        
        public PlayerStatus()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteByte(m_statusId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_statusId = reader.ReadByte();
        }
    }
}
