//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Types.Game.House
{
    using Cookie.API.Utils.IO;

    public class HouseInformationsInside : HouseInformations
    {
        
        public new const short ProtocolId = 218;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }

        private HouseInstanceInformations m_houseInfos;

        public virtual HouseInstanceInformations HouseInfos
        {
            get
            {
                return m_houseInfos;
            }
            set
            {
                m_houseInfos = value;
            }
        }

        private short m_worldX;
        
        public virtual short WorldX
        {
            get
            {
                return m_worldX;
            }
            set
            {
                m_worldX = value;
            }
        }
        
        private short m_worldY;
        
        public virtual short WorldY
        {
            get
            {
                return m_worldY;
            }
            set
            {
                m_worldY = value;
            }
        }
        
        public HouseInformationsInside(HouseInstanceInformations houseInfos, short worldX, short worldY)
        {
            m_worldX = worldX;
            m_worldY = worldY;
            m_houseInfos = houseInfos;
        }
        
        public HouseInformationsInside()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
            writer.WriteUShort(((ushort)(m_houseInfos.TypeID)));
            m_houseInfos.Serialize(writer);
            writer.WriteShort(m_worldX);
            writer.WriteShort(m_worldY);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
            m_houseInfos = ProtocolTypeManager.GetInstance<HouseInstanceInformations>((short)reader.ReadUShort());
            m_houseInfos.Deserialize(reader);
            m_worldX = reader.ReadShort();
            m_worldY = reader.ReadShort();
        }
    }
}
