//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Messages.Game.Context.Display
{
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class DisplayNumericalValueMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5808;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private int m_entityId;
        
        public virtual int EntityId
        {
            get
            {
                return m_entityId;
            }
            set
            {
                m_entityId = value;
            }
        }
        
        private int m_value;
        
        public virtual int Value
        {
            get
            {
                return m_value;
            }
            set
            {
                m_value = value;
            }
        }
        
        private byte m_type;
        
        public virtual byte Type
        {
            get
            {
                return m_type;
            }
            set
            {
                m_type = value;
            }
        }
        
        public DisplayNumericalValueMessage(int entityId, int value, byte type)
        {
            m_entityId = entityId;
            m_value = value;
            m_type = type;
        }
        
        public DisplayNumericalValueMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteInt(m_entityId);
            writer.WriteInt(m_value);
            writer.WriteByte(m_type);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_entityId = reader.ReadInt();
            m_value = reader.ReadInt();
            m_type = reader.ReadByte();
        }
    }
}
