//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class GameFightTurnResumeMessage : GameFightTurnStartMessage
    {
        
        public new const uint ProtocolId = 6307;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_remainingTime;
        
        public virtual uint RemainingTime
        {
            get
            {
                return m_remainingTime;
            }
            set
            {
                m_remainingTime = value;
            }
        }
        
        public GameFightTurnResumeMessage(uint remainingTime)
        {
            m_remainingTime = remainingTime;
        }
        
        public GameFightTurnResumeMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_remainingTime);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
            m_remainingTime = reader.ReadVarUhInt();
        }
    }
}
