//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class GameFightPlacementSwapPositionsCancelledMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6546;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private int m_requestId;
        
        public virtual int RequestId
        {
            get
            {
                return m_requestId;
            }
            set
            {
                m_requestId = value;
            }
        }
        
        private double m_cancellerId;
        
        public virtual double CancellerId
        {
            get
            {
                return m_cancellerId;
            }
            set
            {
                m_cancellerId = value;
            }
        }
        
        public GameFightPlacementSwapPositionsCancelledMessage(int requestId, double cancellerId)
        {
            m_requestId = requestId;
            m_cancellerId = cancellerId;
        }
        
        public GameFightPlacementSwapPositionsCancelledMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteInt(m_requestId);
            writer.WriteDouble(m_cancellerId);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_requestId = reader.ReadInt();
            m_cancellerId = reader.ReadDouble();
        }
    }
}
