//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class ExchangeStartOkNpcTradeMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5785;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private double m_npcId;
        
        public virtual double NpcId
        {
            get
            {
                return m_npcId;
            }
            set
            {
                m_npcId = value;
            }
        }
        
        public ExchangeStartOkNpcTradeMessage(double npcId)
        {
            m_npcId = npcId;
        }
        
        public ExchangeStartOkNpcTradeMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteDouble(m_npcId);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_npcId = reader.ReadDouble();
        }
    }
}
