//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Messages.Game.Context.Roleplay.Quest
{
    using Cookie.Protocol;
    using Cookie.IO;

    public class GuidedModeQuitRequestMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6092;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        public GuidedModeQuitRequestMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
        }
    }
}
