//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Messages.Game.Guild
{
    using Cookie.Protocol.Network.Types.Game.House;
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class GuildHousesInformationMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5919;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private List<HouseInformationsForGuild> m_housesInformations;
        
        public virtual List<HouseInformationsForGuild> HousesInformations
        {
            get
            {
                return m_housesInformations;
            }
            set
            {
                m_housesInformations = value;
            }
        }
        
        public GuildHousesInformationMessage(List<HouseInformationsForGuild> housesInformations)
        {
            m_housesInformations = housesInformations;
        }
        
        public GuildHousesInformationMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteShort(((short)(m_housesInformations.Count)));
            int housesInformationsIndex;
            for (housesInformationsIndex = 0; (housesInformationsIndex < m_housesInformations.Count); housesInformationsIndex = (housesInformationsIndex + 1))
            {
                HouseInformationsForGuild objectToSend = m_housesInformations[housesInformationsIndex];
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            int housesInformationsCount = reader.ReadUShort();
            int housesInformationsIndex;
            m_housesInformations = new System.Collections.Generic.List<HouseInformationsForGuild>();
            for (housesInformationsIndex = 0; (housesInformationsIndex < housesInformationsCount); housesInformationsIndex = (housesInformationsIndex + 1))
            {
                HouseInformationsForGuild objectToAdd = new HouseInformationsForGuild();
                objectToAdd.Deserialize(reader);
                m_housesInformations.Add(objectToAdd);
            }
        }
    }
}
