//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using Cookie.Network;

namespace Cookie.Protocol.Network.Messages.Game.Context.Roleplay
{
    using Cookie.IO;
    using Cookie.Protocol.Network.Types.Game.Context.Roleplay;


    public class GameRolePlayShowActorMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5632;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private GameRolePlayActorInformations m_informations;
        
        public virtual GameRolePlayActorInformations Informations
        {
            get
            {
                return m_informations;
            }
            set
            {
                m_informations = value;
            }
        }
        
        public GameRolePlayShowActorMessage(GameRolePlayActorInformations informations)
        {
            m_informations = informations;
        }
        
        public GameRolePlayShowActorMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteUShort(((ushort)(m_informations.TypeID)));
            m_informations.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_informations = ProtocolTypeManager.GetInstance<GameRolePlayActorInformations>((short)reader.ReadUShort());
            m_informations.Deserialize(reader);
        }
    }
}
