//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class GameFightOptionToggleMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 707;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_option;
        
        public virtual byte Option
        {
            get
            {
                return m_option;
            }
            set
            {
                m_option = value;
            }
        }
        
        public GameFightOptionToggleMessage(byte option)
        {
            m_option = option;
        }
        
        public GameFightOptionToggleMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteByte(m_option);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_option = reader.ReadByte();
        }
    }
}
