//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Enums
{
    
    
    public enum BoostableCharacteristicEnum
    {
        
        BOOSTABLE_CHARAC_STRENGTH = 10,
        
        BOOSTABLE_CHARAC_VITALITY = 11,
        
        BOOSTABLE_CHARAC_WISDOM = 12,
        
        BOOSTABLE_CHARAC_CHANCE = 13,
        
        BOOSTABLE_CHARAC_AGILITY = 14,
        
        BOOSTABLE_CHARAC_INTELLIGENCE = 15,
    }
}
