//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Enums
{
    
    
    public enum CharacterSpellModificationTypeEnum
    {
        
        INVALID_MODIFICATION = 0,
        
        RANGEABLE = 1,
        
        DAMAGE = 2,
        
        BASE_DAMAGE = 3,
        
        HEAL_BONUS = 4,
        
        AP_COST = 5,
        
        CAST_INTERVAL = 6,
        
        CAST_INTERVAL_SET = 7,
        
        CRITICAL_HIT_BONUS = 8,
        
        CAST_LINE = 9,
        
        LOS = 10,
        
        MAX_CAST_PER_TURN = 11,
        
        MAX_CAST_PER_TARGET = 12,
        
        RANGE = 13,
    }
}
