//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Enums
{
    
    
    public enum CharacterRemodelingEnum
    {
        
        CHARACTER_REMODELING_NOT_APPLICABLE = 0,
        
        CHARACTER_REMODELING_NAME = 1,
        
        CHARACTER_REMODELING_COLORS = 2,
        
        CHARACTER_REMODELING_COSMETIC = 4,
        
        CHARACTER_REMODELING_BREED = 8,
        
        CHARACTER_REMODELING_GENDER = 16,
        
        CHARACTER_OPT_REMODELING_NAME = 32,
    }
}
