//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Enums
{
    
    
    public enum ChatChannelsMultiEnum
    {
        
        CHANNEL_GLOBAL = 0,
        
        CHANNEL_TEAM = 1,
        
        CHANNEL_GUILD = 2,
        
        CHANNEL_ALLIANCE = 3,
        
        CHANNEL_PARTY = 4,
        
        CHANNEL_SALES = 5,
        
        CHANNEL_SEEK = 6,
        
        CHANNEL_NOOB = 7,
        
        CHANNEL_ADMIN = 8,
        
        CHANNEL_ADS = 12,
        
        CHANNEL_ARENA = 13,
        
        CHANNEL_COMMUNITY = 14,
    }
}
