//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Enums
{
    
    
    public enum PaymentTypeEnum
    {
        
        PAYMENT_ON_SUCCESS_ONLY = 0,
        
        PAYMENT_IN_ANY_CASE = 1,
    }
}
