//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Enums
{
    
    
    public enum PlayerStatusEnum
    {
        
        PLAYER_STATUS_OFFLINE = 0,
        
        PLAYER_STATUS_UNKNOWN = 1,
        
        PLAYER_STATUS_AVAILABLE = 10,
        
        PLAYER_STATUS_IDLE = 20,
        
        PLAYER_STATUS_AFK = 21,
        
        PLAYER_STATUS_PRIVATE = 30,
        
        PLAYER_STATUS_SOLO = 40,
    }
}
