//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Enums
{
    
    
    public enum PresetSaveResultEnum
    {
        
        PRESET_SAVE_OK = 1,
        
        PRESET_SAVE_ERR_UNKNOWN = 2,
        
        PRESET_SAVE_ERR_TOO_MANY = 3,
    }
}
