//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Enums
{
    
    
    public enum PrismSetSabotagedRefusedReasonEnum
    {
        
        SABOTAGE_INSUFFICIENT_RIGHTS = 0,
        
        SABOTAGE_MEMBER_ACCOUNT_NEEDED = 1,
        
        SABOTAGE_RESTRICTED_ACCOUNT = 2,
        
        SABOTAGE_WRONG_ALLIANCE = 3,
        
        SABOTAGE_NO_PRISM = 4,
        
        SABOTAGE_WRONG_STATE = 5,
    }
}
