//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Types.Game.Actions.Fight
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.IO;
    
    
    public class AbstractFightDispellableEffect : NetworkType
    {
        
        public const short ProtocolId = 206;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_uid;
        
        public virtual uint Uid
        {
            get
            {
                return m_uid;
            }
            set
            {
                m_uid = value;
            }
        }
        
        private double m_targetId;
        
        public virtual double TargetId
        {
            get
            {
                return m_targetId;
            }
            set
            {
                m_targetId = value;
            }
        }
        
        private short m_turnDuration;
        
        public virtual short TurnDuration
        {
            get
            {
                return m_turnDuration;
            }
            set
            {
                m_turnDuration = value;
            }
        }
        
        private byte m_dispelable;
        
        public virtual byte Dispelable
        {
            get
            {
                return m_dispelable;
            }
            set
            {
                m_dispelable = value;
            }
        }
        
        private ushort m_spellId;
        
        public virtual ushort SpellId
        {
            get
            {
                return m_spellId;
            }
            set
            {
                m_spellId = value;
            }
        }
        
        private uint m_effectId;
        
        public virtual uint EffectId
        {
            get
            {
                return m_effectId;
            }
            set
            {
                m_effectId = value;
            }
        }
        
        private uint m_parentBoostUid;
        
        public virtual uint ParentBoostUid
        {
            get
            {
                return m_parentBoostUid;
            }
            set
            {
                m_parentBoostUid = value;
            }
        }
        
        public AbstractFightDispellableEffect(uint uid, double targetId, short turnDuration, byte dispelable, ushort spellId, uint effectId, uint parentBoostUid)
        {
            m_uid = uid;
            m_targetId = targetId;
            m_turnDuration = turnDuration;
            m_dispelable = dispelable;
            m_spellId = spellId;
            m_effectId = effectId;
            m_parentBoostUid = parentBoostUid;
        }
        
        public AbstractFightDispellableEffect()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteVarUhInt(m_uid);
            writer.WriteDouble(m_targetId);
            writer.WriteShort(m_turnDuration);
            writer.WriteByte(m_dispelable);
            writer.WriteVarUhShort(m_spellId);
            writer.WriteVarUhInt(m_effectId);
            writer.WriteVarUhInt(m_parentBoostUid);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_uid = reader.ReadVarUhInt();
            m_targetId = reader.ReadDouble();
            m_turnDuration = reader.ReadShort();
            m_dispelable = reader.ReadByte();
            m_spellId = reader.ReadVarUhShort();
            m_effectId = reader.ReadVarUhInt();
            m_parentBoostUid = reader.ReadVarUhInt();
        }
    }
}
