//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Types.Game.Actions.Fight
{
    using Cookie.API.Utils.IO;


    public class FightTemporaryBoostWeaponDamagesEffect : FightTemporaryBoostEffect
    {
        
        public new const short ProtocolId = 211;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private short m_weaponTypeId;
        
        public virtual short WeaponTypeId
        {
            get
            {
                return m_weaponTypeId;
            }
            set
            {
                m_weaponTypeId = value;
            }
        }
        
        public FightTemporaryBoostWeaponDamagesEffect(short weaponTypeId)
        {
            m_weaponTypeId = weaponTypeId;
        }
        
        public FightTemporaryBoostWeaponDamagesEffect()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(m_weaponTypeId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_weaponTypeId = reader.ReadShort();
        }
    }
}
