//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Types.Game.Mount
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class ItemDurability : NetworkType
    {
        
        public const short ProtocolId = 168;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private short m_durability;
        
        public virtual short Durability
        {
            get
            {
                return m_durability;
            }
            set
            {
                m_durability = value;
            }
        }
        
        private short m_durabilityMax;
        
        public virtual short DurabilityMax
        {
            get
            {
                return m_durabilityMax;
            }
            set
            {
                m_durabilityMax = value;
            }
        }
        
        public ItemDurability(short durability, short durabilityMax)
        {
            m_durability = durability;
            m_durabilityMax = durabilityMax;
        }
        
        public ItemDurability()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteShort(m_durability);
            writer.WriteShort(m_durabilityMax);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_durability = reader.ReadShort();
            m_durabilityMax = reader.ReadShort();
        }
    }
}
