//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Types.Game.Prism
{
    using Cookie.API.Protocol.Network.Types.Game.Context.Roleplay;
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class AlliancePrismInformation : PrismInformation
    {
        
        public new const short ProtocolId = 427;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private AllianceInformations m_alliance;
        
        public virtual AllianceInformations Alliance
        {
            get
            {
                return m_alliance;
            }
            set
            {
                m_alliance = value;
            }
        }
        
        public AlliancePrismInformation(AllianceInformations alliance)
        {
            m_alliance = alliance;
        }
        
        public AlliancePrismInformation()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
            m_alliance.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
            m_alliance = new AllianceInformations();
            m_alliance.Deserialize(reader);
        }
    }
}
