//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Friend
{
    using Cookie.API.IO;
    using Cookie.API.Protocol.Network.Types.Game.Friend;


    public class IgnoredAddedMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5678;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private IgnoredInformations m_ignoreAdded;
        
        public virtual IgnoredInformations IgnoreAdded
        {
            get
            {
                return m_ignoreAdded;
            }
            set
            {
                m_ignoreAdded = value;
            }
        }
        
        private bool m_session;
        
        public virtual bool Session
        {
            get
            {
                return m_session;
            }
            set
            {
                m_session = value;
            }
        }
        
        public IgnoredAddedMessage(IgnoredInformations ignoreAdded, bool session)
        {
            m_ignoreAdded = ignoreAdded;
            m_session = session;
        }
        
        public IgnoredAddedMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteUShort(((ushort)(m_ignoreAdded.TypeID)));
            m_ignoreAdded.Serialize(writer);
            writer.WriteBoolean(m_session);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_ignoreAdded = ProtocolTypeManager.GetInstance<IgnoredInformations>((short)reader.ReadUShort());
            m_ignoreAdded.Deserialize(reader);
            m_session = reader.ReadBoolean();
        }
    }
}
