//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Friend
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class IgnoredAddRequestMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5673;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private string m_name;
        
        public virtual string Name
        {
            get
            {
                return m_name;
            }
            set
            {
                m_name = value;
            }
        }
        
        private bool m_session;
        
        public virtual bool Session
        {
            get
            {
                return m_session;
            }
            set
            {
                m_session = value;
            }
        }
        
        public IgnoredAddRequestMessage(string name, bool session)
        {
            m_name = name;
            m_session = session;
        }
        
        public IgnoredAddRequestMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteUTF(m_name);
            writer.WriteBoolean(m_session);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_name = reader.ReadUTF();
            m_session = reader.ReadBoolean();
        }
    }
}
