//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Enums
{
    
    
    public enum BuildTypeEnum
    {
        
        RELEASE = 0,
        
        BETA = 1,
        
        ALPHA = 2,
        
        TESTING = 3,
        
        INTERNAL = 4,
        
        DEBUG = 5,
        
        EXPERIMENTAL = 6,
    }
}
