//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Enums
{
    
    
    public enum DirectionsEnum
    {
        
        DIRECTION_EAST = 0,
        
        DIRECTION_SOUTH_EAST = 1,
        
        DIRECTION_SOUTH = 2,
        
        DIRECTION_SOUTH_WEST = 3,
        
        DIRECTION_WEST = 4,
        
        DIRECTION_NORTH_WEST = 5,
        
        DIRECTION_NORTH = 6,
        
        DIRECTION_NORTH_EAST = 7,
    }
}
