//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Enums
{
    
    
    public enum PresetUseResultEnum
    {
        
        PRESET_USE_OK = 1,
        
        PRESET_USE_OK_PARTIAL = 2,
        
        PRESET_USE_ERR_UNKNOWN = 3,
        
        PRESET_USE_ERR_CRITERION = 4,
        
        PRESET_USE_ERR_BAD_PRESET_ID = 5,
        
        PRESET_USE_ERR_COOLDOWN = 6,
    }
}
