//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Enums
{
    
    
    public enum SocialGroupInvitationStateEnum
    {
        
        SOCIAL_GROUP_INVITATION_FAILED = 0,
        
        SOCIAL_GROUP_INVITATION_SENT = 1,
        
        SOCIAL_GROUP_INVITATION_CANCELED = 2,
        
        SOCIAL_GROUP_INVITATION_OK = 3,
    }
}
