//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Enums
{
    
    
    public enum TeleporterTypeEnum
    {
        
        TELEPORTER_ZAAP = 0,
        
        TELEPORTER_SUBWAY = 1,
        
        TELEPORTER_PRISM = 2,
        
        TELEPORTER_HAVENBAG = 3,
    }
}
