//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Roleplay.Party
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class PartyInvitationMessage : AbstractPartyMessage
    {
        
        public new const uint ProtocolId = 5586;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_partyType;
        
        public virtual byte PartyType
        {
            get
            {
                return m_partyType;
            }
            set
            {
                m_partyType = value;
            }
        }
        
        private string m_partyName;
        
        public virtual string PartyName
        {
            get
            {
                return m_partyName;
            }
            set
            {
                m_partyName = value;
            }
        }
        
        private byte m_maxParticipants;
        
        public virtual byte MaxParticipants
        {
            get
            {
                return m_maxParticipants;
            }
            set
            {
                m_maxParticipants = value;
            }
        }
        
        private ulong m_fromId;
        
        public virtual ulong FromId
        {
            get
            {
                return m_fromId;
            }
            set
            {
                m_fromId = value;
            }
        }
        
        private string m_fromName;
        
        public virtual string FromName
        {
            get
            {
                return m_fromName;
            }
            set
            {
                m_fromName = value;
            }
        }
        
        private ulong m_toId;
        
        public virtual ulong ToId
        {
            get
            {
                return m_toId;
            }
            set
            {
                m_toId = value;
            }
        }
        
        public PartyInvitationMessage(byte partyType, string partyName, byte maxParticipants, ulong fromId, string fromName, ulong toId)
        {
            m_partyType = partyType;
            m_partyName = partyName;
            m_maxParticipants = maxParticipants;
            m_fromId = fromId;
            m_fromName = fromName;
            m_toId = toId;
        }
        
        public PartyInvitationMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteByte(m_partyType);
            writer.WriteUTF(m_partyName);
            writer.WriteByte(m_maxParticipants);
            writer.WriteVarUhLong(m_fromId);
            writer.WriteUTF(m_fromName);
            writer.WriteVarUhLong(m_toId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_partyType = reader.ReadByte();
            m_partyName = reader.ReadUTF();
            m_maxParticipants = reader.ReadByte();
            m_fromId = reader.ReadVarUhLong();
            m_fromName = reader.ReadUTF();
            m_toId = reader.ReadVarUhLong();
        }
    }
}
