//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Roleplay.Party
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class PartyLeaderUpdateMessage : AbstractPartyEventMessage
    {
        
        public new const uint ProtocolId = 5578;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ulong m_partyLeaderId;
        
        public virtual ulong PartyLeaderId
        {
            get
            {
                return m_partyLeaderId;
            }
            set
            {
                m_partyLeaderId = value;
            }
        }
        
        public PartyLeaderUpdateMessage(ulong partyLeaderId)
        {
            m_partyLeaderId = partyLeaderId;
        }
        
        public PartyLeaderUpdateMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhLong(m_partyLeaderId);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
            m_partyLeaderId = reader.ReadVarUhLong();
        }
    }
}
