//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Messages.Game.Context
{
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class GameContextCreateMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 200;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_context;
        
        public virtual byte Context
        {
            get
            {
                return m_context;
            }
            set
            {
                m_context = value;
            }
        }
        
        public GameContextCreateMessage(byte context)
        {
            m_context = context;
        }
        
        public GameContextCreateMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteByte(m_context);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_context = reader.ReadByte();
        }
    }
}
