//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using Cookie.Network;

namespace Cookie.Protocol.Network.Messages.Game.Context.Fight.Character
{
    using Cookie.Protocol.Network.Types.Game.Context;
    using Cookie.Protocol.Network;
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class GameFightRefreshFighterMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6309;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private GameContextActorInformations m_informations;
        
        public virtual GameContextActorInformations Informations
        {
            get
            {
                return m_informations;
            }
            set
            {
                m_informations = value;
            }
        }
        
        public GameFightRefreshFighterMessage(GameContextActorInformations informations)
        {
            m_informations = informations;
        }
        
        public GameFightRefreshFighterMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteUShort(((ushort)(m_informations.TypeID)));
            m_informations.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_informations = ProtocolTypeManager.GetInstance<GameContextActorInformations>((short)reader.ReadUShort());
            m_informations.Deserialize(reader);
        }
    }
}
