//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Prism
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class PrismInfoJoinLeaveRequestMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5844;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private bool m_join;
        
        public virtual bool Join
        {
            get
            {
                return m_join;
            }
            set
            {
                m_join = value;
            }
        }
        
        public PrismInfoJoinLeaveRequestMessage(bool join)
        {
            m_join = join;
        }
        
        public PrismInfoJoinLeaveRequestMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteBoolean(m_join);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_join = reader.ReadBoolean();
        }
    }
}
