//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Prism
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.IO;
    
    
    public class PrismsListRegisterMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6441;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_listen;
        
        public virtual byte Listen
        {
            get
            {
                return m_listen;
            }
            set
            {
                m_listen = value;
            }
        }
        
        public PrismsListRegisterMessage(byte listen)
        {
            m_listen = listen;
        }
        
        public PrismsListRegisterMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteByte(m_listen);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_listen = reader.ReadByte();
        }
    }
}
