//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Roleplay.Fight
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class GameRolePlayPlayerFightRequestMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5731;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ulong m_targetId;
        
        public virtual ulong TargetId
        {
            get
            {
                return m_targetId;
            }
            set
            {
                m_targetId = value;
            }
        }
        
        private short m_targetCellId;
        
        public virtual short TargetCellId
        {
            get
            {
                return m_targetCellId;
            }
            set
            {
                m_targetCellId = value;
            }
        }
        
        private bool m_friendly;
        
        public virtual bool Friendly
        {
            get
            {
                return m_friendly;
            }
            set
            {
                m_friendly = value;
            }
        }
        
        public GameRolePlayPlayerFightRequestMessage(ulong targetId, short targetCellId, bool friendly)
        {
            m_targetId = targetId;
            m_targetCellId = targetCellId;
            m_friendly = friendly;
        }
        
        public GameRolePlayPlayerFightRequestMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteVarUhLong(m_targetId);
            writer.WriteShort(m_targetCellId);
            writer.WriteBoolean(m_friendly);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_targetId = reader.ReadVarUhLong();
            m_targetCellId = reader.ReadShort();
            m_friendly = reader.ReadBoolean();
        }
    }
}
