//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Types.Game.Context.Roleplay.Job
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class JobCrafterDirectorySettings : NetworkType
    {
        
        public const short ProtocolId = 97;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_jobId;
        
        public virtual byte JobId
        {
            get
            {
                return m_jobId;
            }
            set
            {
                m_jobId = value;
            }
        }
        
        private sbyte m_minLevel;
        
        public virtual sbyte MinLevel
        {
            get
            {
                return m_minLevel;
            }
            set
            {
                m_minLevel = value;
            }
        }
        
        private bool m_free;
        
        public virtual bool Free
        {
            get
            {
                return m_free;
            }
            set
            {
                m_free = value;
            }
        }
        
        public JobCrafterDirectorySettings(byte jobId, sbyte minLevel, bool free)
        {
            m_jobId = jobId;
            m_minLevel = minLevel;
            m_free = free;
        }
        
        public JobCrafterDirectorySettings()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteByte(m_jobId);
            writer.WriteSByte(m_minLevel);
            writer.WriteBoolean(m_free);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_jobId = reader.ReadByte();
            m_minLevel = reader.ReadSByte();
            m_free = reader.ReadBoolean();
        }
    }
}
