//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Roleplay.Death
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class GameRolePlayPlayerLifeStatusMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5996;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_state;
        
        public virtual byte State
        {
            get
            {
                return m_state;
            }
            set
            {
                m_state = value;
            }
        }
        
        private int m_phenixMapId;
        
        public virtual int PhenixMapId
        {
            get
            {
                return m_phenixMapId;
            }
            set
            {
                m_phenixMapId = value;
            }
        }
        
        public GameRolePlayPlayerLifeStatusMessage(byte state, int phenixMapId)
        {
            m_state = state;
            m_phenixMapId = phenixMapId;
        }
        
        public GameRolePlayPlayerLifeStatusMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteByte(m_state);
            writer.WriteInt(m_phenixMapId);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_state = reader.ReadByte();
            m_phenixMapId = reader.ReadInt();
        }
    }
}
