//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Types.Game.Data.Items
{
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class GoldItem : Item
    {
        
        public new const short ProtocolId = 123;
        
        public override short TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ulong m_sum;
        
        public virtual ulong Sum
        {
            get
            {
                return m_sum;
            }
            set
            {
                m_sum = value;
            }
        }
        
        public GoldItem(ulong sum)
        {
            m_sum = sum;
        }
        
        public GoldItem()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhLong(m_sum);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
            m_sum = reader.ReadVarUhLong();
        }
    }
}
