//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Guild
{
    using Cookie.API.Protocol.Network.Types.Game.Context.Roleplay;
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class GuildInvitedMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5552;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private BasicGuildInformations m_guildInfo;
        
        public virtual BasicGuildInformations GuildInfo
        {
            get
            {
                return m_guildInfo;
            }
            set
            {
                m_guildInfo = value;
            }
        }
        
        private ulong m_recruterId;
        
        public virtual ulong RecruterId
        {
            get
            {
                return m_recruterId;
            }
            set
            {
                m_recruterId = value;
            }
        }
        
        private string m_recruterName;
        
        public virtual string RecruterName
        {
            get
            {
                return m_recruterName;
            }
            set
            {
                m_recruterName = value;
            }
        }
        
        public GuildInvitedMessage(BasicGuildInformations guildInfo, ulong recruterId, string recruterName)
        {
            m_guildInfo = guildInfo;
            m_recruterId = recruterId;
            m_recruterName = recruterName;
        }
        
        public GuildInvitedMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_guildInfo.Serialize(writer);
            writer.WriteVarUhLong(m_recruterId);
            writer.WriteUTF(m_recruterName);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_guildInfo = new BasicGuildInformations();
            m_guildInfo.Deserialize(reader);
            m_recruterId = reader.ReadVarUhLong();
            m_recruterName = reader.ReadUTF();
        }
    }
}
