//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Guild
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class GuildKickRequestMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5887;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ulong m_kickedId;
        
        public virtual ulong KickedId
        {
            get
            {
                return m_kickedId;
            }
            set
            {
                m_kickedId = value;
            }
        }
        
        public GuildKickRequestMessage(ulong kickedId)
        {
            m_kickedId = kickedId;
        }
        
        public GuildKickRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhLong(m_kickedId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_kickedId = reader.ReadVarUhLong();
        }
    }
}
