//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Web.Haapi
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.Utils.IO;
    
    
    public class HaapiApiKeyMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6649;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_returnType;
        
        public virtual byte ReturnType
        {
            get
            {
                return m_returnType;
            }
            set
            {
                m_returnType = value;
            }
        }
        
        private byte m_keyType;
        
        public virtual byte KeyType
        {
            get
            {
                return m_keyType;
            }
            set
            {
                m_keyType = value;
            }
        }
        
        private string m_token;
        
        public virtual string Token
        {
            get
            {
                return m_token;
            }
            set
            {
                m_token = value;
            }
        }
        
        public HaapiApiKeyMessage(byte returnType, byte keyType, string token)
        {
            m_returnType = returnType;
            m_keyType = keyType;
            m_token = token;
        }
        
        public HaapiApiKeyMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteByte(m_returnType);
            writer.WriteByte(m_keyType);
            writer.WriteUTF(m_token);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_returnType = reader.ReadByte();
            m_keyType = reader.ReadByte();
            m_token = reader.ReadUTF();
        }
    }
}
