//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Context.Roleplay.Paddock
{
    using Cookie.API.Protocol.Network.Types.Game.Paddock;
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.IO;
    
    
    public class PaddockToSellListMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6138;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private List<PaddockInformationsForSell> m_paddockList;
        
        public virtual List<PaddockInformationsForSell> PaddockList
        {
            get
            {
                return m_paddockList;
            }
            set
            {
                m_paddockList = value;
            }
        }
        
        private ushort m_pageIndex;
        
        public virtual ushort PageIndex
        {
            get
            {
                return m_pageIndex;
            }
            set
            {
                m_pageIndex = value;
            }
        }
        
        private ushort m_totalPage;
        
        public virtual ushort TotalPage
        {
            get
            {
                return m_totalPage;
            }
            set
            {
                m_totalPage = value;
            }
        }
        
        public PaddockToSellListMessage(List<PaddockInformationsForSell> paddockList, ushort pageIndex, ushort totalPage)
        {
            m_paddockList = paddockList;
            m_pageIndex = pageIndex;
            m_totalPage = totalPage;
        }
        
        public PaddockToSellListMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteShort(((short)(m_paddockList.Count)));
            int paddockListIndex;
            for (paddockListIndex = 0; (paddockListIndex < m_paddockList.Count); paddockListIndex = (paddockListIndex + 1))
            {
                PaddockInformationsForSell objectToSend = m_paddockList[paddockListIndex];
                objectToSend.Serialize(writer);
            }
            writer.WriteVarUhShort(m_pageIndex);
            writer.WriteVarUhShort(m_totalPage);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            int paddockListCount = reader.ReadUShort();
            int paddockListIndex;
            m_paddockList = new System.Collections.Generic.List<PaddockInformationsForSell>();
            for (paddockListIndex = 0; (paddockListIndex < paddockListCount); paddockListIndex = (paddockListIndex + 1))
            {
                PaddockInformationsForSell objectToAdd = new PaddockInformationsForSell();
                objectToAdd.Deserialize(reader);
                m_paddockList.Add(objectToAdd);
            }
            m_pageIndex = reader.ReadVarUhShort();
            m_totalPage = reader.ReadVarUhShort();
        }
    }
}
