//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.Protocol.Network.Messages.Game.Context.Dungeon
{
    using System.Collections.Generic;
    using Cookie.Protocol.Network.Messages;
    using Cookie.Protocol.Network.Types;
    using Cookie.IO;
    
    
    public class DungeonKeyRingMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 6299;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private List<System.UInt16> m_availables;
        
        public virtual List<System.UInt16> Availables
        {
            get
            {
                return m_availables;
            }
            set
            {
                m_availables = value;
            }
        }
        
        private List<System.UInt16> m_unavailables;
        
        public virtual List<System.UInt16> Unavailables
        {
            get
            {
                return m_unavailables;
            }
            set
            {
                m_unavailables = value;
            }
        }
        
        public DungeonKeyRingMessage(List<System.UInt16> availables, List<System.UInt16> unavailables)
        {
            m_availables = availables;
            m_unavailables = unavailables;
        }
        
        public DungeonKeyRingMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteShort(((short)(m_availables.Count)));
            int availablesIndex;
            for (availablesIndex = 0; (availablesIndex < m_availables.Count); availablesIndex = (availablesIndex + 1))
            {
                writer.WriteVarUhShort(m_availables[availablesIndex]);
            }
            writer.WriteShort(((short)(m_unavailables.Count)));
            int unavailablesIndex;
            for (unavailablesIndex = 0; (unavailablesIndex < m_unavailables.Count); unavailablesIndex = (unavailablesIndex + 1))
            {
                writer.WriteVarUhShort(m_unavailables[unavailablesIndex]);
            }
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            int availablesCount = reader.ReadUShort();
            int availablesIndex;
            m_availables = new System.Collections.Generic.List<ushort>();
            for (availablesIndex = 0; (availablesIndex < availablesCount); availablesIndex = (availablesIndex + 1))
            {
                m_availables.Add(reader.ReadVarUhShort());
            }
            int unavailablesCount = reader.ReadUShort();
            int unavailablesIndex;
            m_unavailables = new System.Collections.Generic.List<ushort>();
            for (unavailablesIndex = 0; (unavailablesIndex < unavailablesCount); unavailablesIndex = (unavailablesIndex + 1))
            {
                m_unavailables.Add(reader.ReadVarUhShort());
            }
        }
    }
}
