//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.IO;
    
    
    public class ExchangeRequestOnTaxCollectorMessage : NetworkMessage
    {
        
        public const uint ProtocolId = 5779;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private int m_taxCollectorId;
        
        public virtual int TaxCollectorId
        {
            get
            {
                return m_taxCollectorId;
            }
            set
            {
                m_taxCollectorId = value;
            }
        }
        
        public ExchangeRequestOnTaxCollectorMessage(int taxCollectorId)
        {
            m_taxCollectorId = taxCollectorId;
        }
        
        public ExchangeRequestOnTaxCollectorMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            writer.WriteInt(m_taxCollectorId);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            m_taxCollectorId = reader.ReadInt();
        }
    }
}
