//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookie.API.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using Cookie.API.Protocol.Network.Messages;
    using Cookie.API.Protocol.Network.Types;
    using Cookie.API.IO;
    
    
    public class ExchangeStartedWithStorageMessage : ExchangeStartedMessage
    {
        
        public new const uint ProtocolId = 6236;
        
        public override uint MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_storageMaxSlot;
        
        public virtual uint StorageMaxSlot
        {
            get
            {
                return m_storageMaxSlot;
            }
            set
            {
                m_storageMaxSlot = value;
            }
        }
        
        public ExchangeStartedWithStorageMessage(uint storageMaxSlot)
        {
            m_storageMaxSlot = storageMaxSlot;
        }
        
        public ExchangeStartedWithStorageMessage()
        {
        }
        
        public override void Serialize(ICustomDataOutput writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_storageMaxSlot);
        }
        
        public override void Deserialize(ICustomDataInput reader)
        {
            base.Deserialize(reader);
            m_storageMaxSlot = reader.ReadVarUhInt();
        }
    }
}
